"""Reconstruction: what lands, what does not, and what a failure leaves behind.

Every test here runs on both dialects. The Postgres cases are not decoration:
``audit_log.id`` renders as ``BIGINT GENERATED ALWAYS AS IDENTITY`` and
``object_edits.seq`` as ``GENERATED BY DEFAULT``, so an import that carried
either would be rejected on one backend and silently poison a sequence on the
other — and neither failure is reachable from SQLite.
"""

import io
import json
import os
import tarfile
import uuid

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from laurelin.catalog import DatasetCatalog
from laurelin.core.config import Workspace
from laurelin.core.db import MetadataStore
from laurelin.core.models import (
    EditKind,
    Grant,
    ObjectEdit,
    ScheduleInfo,
    SubjectKind,
)
from laurelin.export import (
    ExportOptions,
    ImportOptions,
    ImportRefused,
    export_workspace,
    import_workspace,
    pipelines_acknowledged,
    read_manifest,
    require_pipelines_acknowledged,
    target_is_pristine,
)
from laurelin.export.manifest import MANIFEST_MEMBER

PG_URL = os.environ.get("LAURELIN_TEST_POSTGRES")

PIPELINE = (
    "from laurelin.transforms import transform, Input, Output\n"
    "@transform(output=Output('derived'), s=Input('sales'))\n"
    "def derive(s):\n    return s\n"
)


@pytest.fixture(params=["sqlite", "postgres"])
def dialect(request):
    if request.param == "postgres" and not PG_URL:
        pytest.skip("set LAURELIN_TEST_POSTGRES to a postgresql:// URL to run")
    return request.param


@pytest.fixture()
def make_store(dialect):
    """A store factory that gives each workspace its own namespace.

    On Postgres that is a schema per workspace — the same mechanism production
    multi-workspace deployments use — so source and target really are two
    stores rather than one wearing two names.
    """
    schemas: list[str] = []

    def factory(workspace: Workspace) -> MetadataStore:
        if dialect == "sqlite":
            return MetadataStore(workspace.metadata_path)
        schema = "lx_" + uuid.uuid4().hex[:12]
        schemas.append(schema)
        return MetadataStore(PG_URL, schema=schema)

    yield factory

    if schemas:
        import psycopg

        with psycopg.connect(PG_URL) as conn:
            for schema in schemas:
                conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            conn.commit()


@pytest.fixture()
def source(tmp_path, make_store):
    workspace = Workspace.init(tmp_path / "src", name="Acme Production")
    store = make_store(workspace)
    catalog = DatasetCatalog(workspace, store)
    catalog.write("sales", pa.table({"region": ["eu", "us"], "amount": [1, 2]}))
    catalog.write("derived", pa.table({"region": ["eu"], "amount": [1]}))
    store.replace_lineage_for_transform("derive", _edges("sales", "derived"))
    store.create_marking("pii")
    store.set_explicit_markings("sales", ["pii"])
    store.recompute_all_markings()
    store.create_group("analysts", "2026-01-01T00:00:00Z")
    store.set_group_members("analysts", ["vic"])
    store.set_grants_for_dataset("sales", [
        Grant(subject_kind=SubjectKind.group, subject="analysts",
              can_view=True).model_dump()
    ])
    store.set_clearances("vic", ["pii"])
    (workspace.pipelines_dir / "p.py").write_text(PIPELINE)
    (workspace.ontology_dir / "o.yml").write_text(
        "object_types:\n"
        "  - api_name: sale\n"
        "    backing_dataset: sales\n"
        "    primary_key: region\n"
        "    properties:\n"
        "      region: {type: string}\n"
    )
    return workspace, store


def _edges(upstream, downstream):
    from laurelin.core.models import LineageEdge

    return [LineageEdge(upstream_dataset=upstream, downstream_dataset=downstream,
                        transform_name="derive")]


@pytest.fixture()
def target(tmp_path, make_store):
    workspace = Workspace.init(tmp_path / "dst", name="dst")
    return workspace, make_store(workspace)


def _roundtrip(source, target, tmp_path, options=None, **export_kwargs):
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / f"export-{uuid.uuid4().hex[:6]}.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions(**export_kwargs))
    report = import_workspace(archive, dst_ws, dst_store, options or ImportOptions())
    return archive, report


# --------------------------------------------------------------------------- shape

def test_an_import_into_a_fresh_workspace_lands_every_rule(source, target, tmp_path):
    _, report = _roundtrip(source, target, tmp_path)
    dst_ws, dst_store = target
    assert report.applied
    assert {d.name for d in dst_store.list_datasets()} == {"sales", "derived"}
    assert len(dst_store.grants_for_dataset("sales")) == 1
    assert DatasetCatalog(dst_ws, dst_store).read("sales").num_rows == 2


def test_import_refuses_a_non_empty_workspace_by_default(source, target, tmp_path):
    """With username and marking name as the only join keys, an existing group
    starts matching the imported grants the instant the rows land."""
    dst_ws, dst_store = target
    dst_store.upsert_dataset("preexisting", "already here")
    assert target_is_pristine(dst_store, dst_ws)[1] == {"datasets": 1}

    with pytest.raises(ImportRefused, match="not empty"):
        _roundtrip(source, target, tmp_path)


def test_a_merge_needs_the_digest_of_the_report_the_operator_read(
    source, target, tmp_path
):
    """The token is the digest of the report, so a report that changed between
    read and apply refuses rather than applying something else."""
    dst_ws, dst_store = target
    dst_store.upsert_dataset("preexisting", "already here")

    src_ws, src_store = source
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    with pytest.raises(ImportRefused, match="digest of the report"):
        import_workspace(archive, dst_ws, dst_store, ImportOptions(merge=True))

    planned = import_workspace(
        archive, dst_ws, dst_store, ImportOptions(merge=True, dry_run=True)
    )
    assert planned.applied is False
    assert planned.report_sha256

    with pytest.raises(ImportRefused, match="digest of the report"):
        import_workspace(
            archive, dst_ws, dst_store,
            ImportOptions(merge=True, confirm="0" * 64),
        )

    applied = import_workspace(
        archive, dst_ws, dst_store,
        ImportOptions(merge=True, confirm=planned.report_sha256),
    )
    assert applied.applied is True


def test_a_dataset_name_collision_refuses_unless_it_is_renamed(
    source, target, tmp_path
):
    """Two different tables claiming one identity has no safe merge."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    dst_store.upsert_dataset("sales", "a different sales table")
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    with pytest.raises(ImportRefused, match="no safe merge"):
        import_workspace(archive, dst_ws, dst_store, ImportOptions(merge=True))

    planned = import_workspace(
        archive, dst_ws, dst_store,
        ImportOptions(merge=True, dry_run=True, rename_prefix="src_"),
    )
    assert planned.dataset_renames == {"sales": "src_sales"}
    import_workspace(
        archive, dst_ws, dst_store,
        ImportOptions(merge=True, rename_prefix="src_",
                      confirm=planned.report_sha256),
    )
    names = {d.name for d in dst_store.list_datasets()}
    assert {"sales", "src_sales", "derived"} <= names
    assert dst_store.grants_for_dataset("src_sales")


def test_a_marking_name_collision_is_namespaced_rather_than_reused(
    source, target, tmp_path
):
    src_ws, src_store = source
    dst_ws, dst_store = target
    dst_store.create_marking("pii", "a different pii, defined locally")
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    planned = import_workspace(
        archive, dst_ws, dst_store, ImportOptions(merge=True, dry_run=True)
    )
    slug = planned.manifest.origin.origin_slug
    assert planned.marking_renames == {"pii": f"pii.{slug}"}

    import_workspace(
        archive, dst_ws, dst_store,
        ImportOptions(merge=True, confirm=planned.report_sha256),
    )
    assert dst_store.get_effective_markings("sales") == [f"pii.{slug}"]


def test_a_group_name_collision_is_reported_as_a_widening_risk(
    source, target, tmp_path
):
    """Measured: making the destination's analysts contain an outsider flipped
    that outsider from (False, False) to (True, False)."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    dst_store.create_group("analysts", "2026-02-01T00:00:00Z")
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    planned = import_workspace(
        archive, dst_ws, dst_store, ImportOptions(merge=True, dry_run=True)
    )
    risks = [c for c in planned.collisions if c.severity == "widening-risk"]
    assert [(r.kind, r.name) for r in risks] == [("group", "analysts")]
    assert "sales" in risks[0].detail


# --------------------------------------------------------------------------- content

def test_import_order_lands_groups_before_the_grants_that_name_them(
    source, target, tmp_path
):
    from laurelin.export.manifest import exported_tables

    order = exported_tables()
    assert order.index("groups") < order.index("dataset_grants")
    assert order.index("markings") < order.index("dataset_markings")
    assert order.index("datasets") < order.index("dataset_versions")

    _, report = _roundtrip(source, target, tmp_path)
    _, dst_store = target
    assert [g["name"] for g in dst_store.list_groups()] == ["analysts"]
    assert report.rows_imported["dataset_grants"] == 1


def test_a_grant_whose_subject_does_not_resolve_is_imported_not_dropped(
    source, target, tmp_path
):
    """The fail-open regression. Measured: emptying a dataset's grant list
    flips it from an allowlist to readable-by-every-authenticated-viewer, so
    dropping an unresolvable grant would *widen*."""
    _roundtrip(source, target, tmp_path)
    _, dst_store = target
    from laurelin.core.models import Role, User
    from laurelin.core.permissions import PermissionService

    assert dst_store.get_user("vic") is None, "import must not create principals"
    assert len(dst_store.grants_for_dataset("sales")) == 1
    outsider = User(id="9", username="mal", role=Role.viewer)
    assert PermissionService(dst_store).dataset_permission(outsider, "sales") == (
        False, False
    )


def test_group_membership_and_clearances_travel_but_are_never_applied(
    source, target, tmp_path
):
    """They are the two row types whose only possible effect is to widen, so
    they arrive as a checklist rather than as state."""
    archive, report = _roundtrip(source, target, tmp_path)
    _, dst_store = target
    assert report.rows_quarantined == {"group_members": 1, "clearances": 1}
    assert dst_store.groups_for_user("vic") == set()
    assert dst_store.get_clearances("vic") == []

    raw = archive.read_bytes()
    assert b'"analysts"' in raw and b'"vic"' in raw  # carried, just not bound


def test_imported_schedules_land_disabled_and_keep_their_watermark(
    source, target, tmp_path
):
    """scheduler.py treats a null watermark as 'fire now', so dropping it makes
    every upstream-triggered schedule fire the moment it is enabled."""
    src_ws, src_store = source
    src_store.upsert_schedule(ScheduleInfo(
        name="nightly", enabled=True, trigger="on_upstream",
        upstream_dataset="sales", action="build", targets=["derived"],
        watermark=7, created_at="2026-01-01T00:00:00Z", created_by="andy",
        last_status="ok", last_error="connect failed to db.internal",
        next_run_at="2026-01-02T00:00:00Z",
    ))
    _roundtrip(source, target, tmp_path)
    _, dst_store = target
    landed = dst_store.get_schedule("nightly")
    assert landed.enabled is False
    assert landed.watermark == 7
    assert landed.next_run_at is None
    assert landed.last_error is None


def test_the_object_index_is_rebuilt_rather_than_imported(source, target, tmp_path):
    """props_json is an UNMASKED materialization of governed rows, and
    _state_is_current never checks the digest on the read path — so an index
    arriving without its FTS mirror would report caught-up and serve rows the
    scan path would not produce."""
    src_ws, src_store = source
    src_store.replace_object_index(
        "sale",
        [{"pk": "eu", "ord": 0, "title": "eu", "search_text": "eu",
          "props_json": json.dumps({"region": "eu", "ssn": "SECRET-CELL"})}],
        dataset_version=1, applied_seq=0,
    )
    archive, _ = _roundtrip(source, target, tmp_path)
    names = _names(archive.read_bytes())
    assert "tables/object_index.jsonl" not in names
    assert "tables/object_index_state.jsonl" not in names
    assert b"SECRET-CELL" not in archive.read_bytes()

    _, dst_store = target
    assert dst_store.object_index_state("sale") is None


def test_effective_markings_are_recomputed_from_lineage_not_copied(
    source, target, tmp_path
):
    """Measured: dropping lineage_edges and recomputing declassified the
    downstream dataset from ['pii'] to [], flipping an outsider to (True,
    False). So the edges are portable and the inherited rows are not."""
    _, src_store = source
    assert src_store.get_effective_markings("derived") == ["pii"]

    archive, _ = _roundtrip(source, target, tmp_path)
    _, dst_store = target
    assert dst_store.get_explicit_markings("derived") == []
    assert dst_store.get_effective_markings("derived") == ["pii"]

    rows = [
        json.loads(line)
        for line in _member(archive.read_bytes(), "tables/dataset_markings.jsonl")
        .splitlines()
    ]
    assert all(r["inherited"] == 0 for r in rows), (
        "inherited rows are the output of the closure, not an input to it"
    )


def test_audit_ids_are_reassigned_and_ordering_survives(source, target, tmp_path):
    """On Postgres audit_log.id is GENERATED ALWAYS AS IDENTITY and rejects an
    explicit insert; list_audit orders by id DESC, so reassignment has to
    preserve order rather than merely not crash."""
    _, src_store = source
    for n in range(5):
        src_store.log_audit(f"action_{n}", {"n": n, "password": "hunter2"},
                            actor="andy")
    _roundtrip(source, target, tmp_path)
    _, dst_store = target
    landed = dst_store.list_audit(limit=100)
    actions = [e.action for e in landed if e.action.startswith("action_")]
    assert actions == ["action_4", "action_3", "action_2", "action_1", "action_0"]
    assert all(e.details.get("password") is None
               for e in landed if e.action.startswith("action_"))
    assert {e.details.get("n") for e in landed if e.action.startswith("action_")} == {
        0, 1, 2, 3, 4
    }


def test_object_edit_seq_values_are_carried_verbatim_and_not_renumbered(
    source, target, tmp_path
):
    """edit_seq is a log position: conflicts are resolved by it, never by
    arrival order, so renumbering would silently reorder resolution."""
    _, src_store = source
    for pk in ("a", "b", "c"):
        src_store.add_object_edit(ObjectEdit(
            id=f"edit-{pk}", object_type="sale", pk_value=pk,
            kind=EditKind.update, payload={"region": pk}, actor="andy",
        ))
    before = [(e.id, e.edit_seq) for e in src_store.list_object_edits("sale")]
    assert len({s for _, s in before}) == 3

    _roundtrip(source, target, tmp_path)
    _, dst_store = target
    after = [(e.id, e.edit_seq) for e in dst_store.list_object_edits("sale")]
    assert after == before


def test_a_metadata_only_import_leaves_the_data_loudly_missing(
    source, target, tmp_path
):
    """Loud, not empty: a managed dataset whose parts never travelled must
    refuse rather than return zero rows."""
    from laurelin.export import NeedsCredentials

    _roundtrip(source, target, tmp_path, metadata_only=True)
    dst_ws, dst_store = target
    with pytest.raises(NeedsCredentials, match="without its data"):
        DatasetCatalog(dst_ws, dst_store).read("sales")


# --------------------------------------------------------------------------- safety

@pytest.mark.parametrize(
    "name, kind",
    [
        ("../../etc/passwd", tarfile.REGTYPE),
        ("/etc/passwd", tarfile.REGTYPE),
        ("tables/../../etc/passwd", tarfile.REGTYPE),
        ("ontology/evil.yml", tarfile.SYMTYPE),
        ("pipelines/evil.py", tarfile.LNKTYPE),
        ("etc/passwd", tarfile.REGTYPE),
    ],
)
def test_a_tar_member_escaping_the_workspace_is_refused(
    source, target, tmp_path, name, kind
):
    """`filter="data"` is a default that differs across the supported range, so
    member names are validated independently of it."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    good = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, good, ExportOptions())

    hostile = io.BytesIO()
    with tarfile.open(fileobj=hostile, mode="w") as out:
        with tarfile.open(good, mode="r") as src:
            manifest = src.getmember(MANIFEST_MEMBER)
            out.addfile(manifest, src.extractfile(manifest))
        info = tarfile.TarInfo(name)
        info.type = kind
        if kind == tarfile.REGTYPE:
            info.size = 5
            out.addfile(info, io.BytesIO(b"pwned"))
        else:
            info.linkname = "../../etc/passwd"
            out.addfile(info)
    hostile.seek(0)

    with pytest.raises(ImportRefused):
        import_workspace(hostile, dst_ws, dst_store, ImportOptions())
    assert not (dst_ws.root / "etc").exists()


def test_a_future_format_version_is_refused_rather_than_guessed_at(
    source, target, tmp_path
):
    src_ws, src_store = source
    dst_ws, dst_store = target
    good = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, good, ExportOptions())

    forged = io.BytesIO()
    with tarfile.open(good, mode="r") as src, tarfile.open(fileobj=forged, mode="w") as out:
        for member in src:
            payload = src.extractfile(member).read()
            if member.name == MANIFEST_MEMBER:
                doc = json.loads(payload)
                doc["format_version"] = 99
                payload = json.dumps(doc).encode()
                member.size = len(payload)
            out.addfile(member, io.BytesIO(payload))
    forged.seek(0)

    with pytest.raises(ImportRefused, match="format_version 99"):
        import_workspace(forged, dst_ws, dst_store, ImportOptions())


def test_imported_pipelines_do_not_execute_until_an_admin_acknowledges_them(
    source, target, tmp_path
):
    """transforms/api.py execs every .py in pipelines/ unsandboxed, so an
    import that ran them would be remote code execution dressed as data
    movement."""
    _roundtrip(source, target, tmp_path)
    dst_ws, dst_store = target
    assert (dst_ws.pipelines_dir / "p.py").exists()
    assert pipelines_acknowledged(dst_ws) is False
    with pytest.raises(ImportRefused, match="acknowledged"):
        require_pipelines_acknowledged(dst_ws)

    from laurelin.export import acknowledge_pipelines

    acknowledge_pipelines(dst_ws, dst_store, actor="ada")
    assert pipelines_acknowledged(dst_ws) is True
    require_pipelines_acknowledged(dst_ws)


def test_a_failed_import_leaves_no_half_populated_workspace(
    source, target, tmp_path, monkeypatch
):
    """Every metadata row lands in one transaction, and parts written before
    the failure are unreferenced garbage rather than a registered version."""
    from laurelin.export import reader

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    real, calls = reader._write_part, {"n": 0}

    def explode(storage, key, spilled):
        # Fail on the *second* part, so the first one is genuinely on disk when
        # the rollback happens. A failure before any write proves nothing.
        calls["n"] += 1
        if calls["n"] > 1:
            raise OSError("storage went away mid-import")
        return real(storage, key, spilled)

    monkeypatch.setattr(reader, "_write_part", explode)

    with pytest.raises(OSError, match="storage went away"):
        import_workspace(archive, dst_ws, dst_store, ImportOptions())

    assert dst_store.list_datasets() == []
    assert dst_store.list_markings() == []
    assert list(dst_ws.data_dir.rglob("*.parquet")) == []
    assert list(dst_ws.root.glob(".laurelin-import-*")) == []


def test_the_manifest_can_be_read_without_consuming_the_archive(
    source, target, tmp_path
):
    """The dry run prints the withheld list and the rebind checklist without
    reading a terabyte of Parquet — which is only possible because the manifest
    is the first member."""
    src_ws, src_store = source
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())
    manifest = read_manifest(archive)
    assert manifest.origin.workspace_name == "Acme Production"
    assert {p.name for p in manifest.principals} == {"analysts", "vic"}


# --------------------------------------------------------------------------- helpers

def _names(raw: bytes) -> list[str]:
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r|*") as tar:
        return [m.name for m in tar]


def _member(raw: bytes, name: str) -> str:
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r|*") as tar:
        for member in tar:
            if member.name == name:
                return tar.extractfile(member).read().decode()
    raise AssertionError(f"no member {name!r}")


def _repack(archive, tmp_path, *, replace=None, extra=(), drop=(), retrailer=True):
    """Rewrite an archive, recomputing TRAILER.json unless told not to.

    Recomputed by default so a test exercises the defence it is about instead
    of stopping at the digest check — which would make every one of these pass
    for the same reason and prove only that one thing.
    """
    import hashlib

    replace = replace or {}
    kept: list[tuple[str, bytes]] = []
    with tarfile.open(archive, mode="r|*") as src:
        for member in src:
            if member.name in drop:
                continue
            payload = src.extractfile(member).read()
            kept.append((member.name, replace.get(member.name, payload)))
    for name, payload in extra:
        kept.insert(1, (name, payload))

    if retrailer:
        digests = {
            name: {"sha256": hashlib.sha256(body).hexdigest(), "bytes": len(body)}
            for name, body in kept if name != "TRAILER.json"
        }
        trailer = json.dumps({
            "members": digests, "member_count": len(digests),
            "total_bytes": sum(d["bytes"] for d in digests.values()),
        }).encode()
        kept = [(n, trailer if n == "TRAILER.json" else b) for n, b in kept]

    out = io.BytesIO()
    with tarfile.open(fileobj=out, mode="w") as tar:
        for name, body in kept:
            info = tarfile.TarInfo(name)
            info.size = len(body)
            info.mode = 0o600
            tar.addfile(info, io.BytesIO(body))
    out.seek(0)
    return out


def _rows_of(archive, table):
    return [
        json.loads(line)
        for line in _member(archive.read_bytes(), f"tables/{table}.jsonl").splitlines()
        if line.strip()
    ]


def _as_jsonl(rows):
    return b"".join(json.dumps(r).encode() + b"\n" for r in rows)


# --------------------------------------------------------------------------- what an
# --------------------------------------------------------------------------- archive
# --------------------------------------------------------------------------- may say

def test_a_part_key_that_leaves_the_workspace_is_refused(source, target, tmp_path):
    """Storage.resolve is an f-string with lstrip('/') and no containment
    check, and catalog.version_files hands its result to pyarrow. Measured
    before this refusal existed: an archive whose files_json said
    '../tenant_b.parquet' — carrying governance the same archive authored —
    served a sibling workspace directory's Parquet through GET /rows."""
    import pyarrow.parquet as pq

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())
    pq.write_table(pa.table({"other_tenant_ssn": ["111-22-3333"]}),
                   tmp_path / "tenant_b.parquet")

    versions = [
        dict(row, files_json=json.dumps(["../tenant_b.parquet"]))
        for row in _rows_of(archive, "dataset_versions")
    ]
    hostile = _repack(archive, tmp_path, replace={
        "tables/dataset_versions.jsonl": _as_jsonl(versions),
    })

    with pytest.raises(ImportRefused, match="leaves the workspace"):
        import_workspace(hostile, dst_ws, dst_store, ImportOptions())
    assert dst_store.list_datasets() == []


def test_a_member_the_trailer_does_not_vouch_for_is_refused(source, target, tmp_path):
    """The per-member digests were parsed and then never compared to anything.
    Measured: two governance members replaced, TRAILER.json left byte-identical
    — a stripped marking and a grant widened to everyone/can_edit imported
    clean, with no warning and a successful workspace_imported audit line."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    widened = _as_jsonl([{
        "id": "forged", "dataset": "sales", "subject_kind": "everyone",
        "subject": "", "can_view": 1, "can_edit": 1,
        "created_at": "2026-01-01T00:00:00Z",
    }])
    tampered = _repack(archive, tmp_path, retrailer=False, replace={
        "tables/dataset_grants.jsonl": widened,
        "tables/dataset_markings.jsonl": b"",
    })

    with pytest.raises(ImportRefused, match="TRAILER.json"):
        import_workspace(tampered, dst_ws, dst_store, ImportOptions())
    assert dst_store.list_datasets() == []


def test_a_table_member_that_declares_more_than_the_ceiling_is_refused(
    source, target, tmp_path
):
    """Measured: a 514 KiB gzipped archive declaring a 512 MiB audit_log member
    took the importer from 172 MiB to 4794 MiB of RSS and then reported a
    successful import. The declared size is in the header, so it costs nothing
    to refuse before reading."""
    from laurelin.export.reader import MAX_TABLE_MEMBER_BYTES

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    bomb = tmp_path / "bomb.tar.gz"
    size = MAX_TABLE_MEMBER_BYTES + 1

    class _Filler(io.RawIOBase):
        def readable(self):
            return True

        def read(self, n=-1):
            return b"\n" * min(n if n and n > 0 else 65536, 1 << 20)

    with tarfile.open(bomb, "w:gz") as out, tarfile.open(archive, "r|*") as src:
        for member in src:
            payload = src.extractfile(member).read()
            info = tarfile.TarInfo(member.name)
            info.size = len(payload)
            out.addfile(info, io.BytesIO(payload))
            if member.name == MANIFEST_MEMBER:
                info = tarfile.TarInfo("tables/audit_log.jsonl")
                info.size = size
                out.addfile(info, _Filler())

    assert bomb.stat().st_size < (2 << 20), "the bomb must be cheap to build"
    with pytest.raises(ImportRefused, match="ceiling"):
        import_workspace(bomb, dst_ws, dst_store, ImportOptions())


def test_a_member_that_appears_twice_is_refused(source, target, tmp_path):
    """Measured: the second copy silently replaced the first, with no warning
    and member_count still agreeing with itself."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    doubled = _repack(archive, tmp_path, extra=[
        ("tables/dataset_grants.jsonl", _as_jsonl([{
            "id": "forged", "dataset": "sales", "subject_kind": "everyone",
            "subject": "", "can_view": 1, "can_edit": 1,
            "created_at": "2026-01-01T00:00:00Z",
        }])),
    ])
    with pytest.raises(ImportRefused, match="appears twice"):
        import_workspace(doubled, dst_ws, dst_store, ImportOptions())


def test_a_member_name_that_is_not_in_normal_form_is_refused(source, target, tmp_path):
    """'ontology/.' passed every check there was: Path('ontology/.').parts is
    ('ontology',), so the '..' test never saw it. Landing it chmod'd the
    workspace's ontology *directory* to 0600 and stripped its traverse bit."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    before = dst_ws.ontology_dir.stat().st_mode & 0o777
    hostile = _repack(archive, tmp_path, extra=[("ontology/.", b"x\n")])
    with pytest.raises(ImportRefused, match="normal form"):
        import_workspace(hostile, dst_ws, dst_store, ImportOptions())
    # Compared against the mode the directory had, not against a literal:
    # `Workspace.init` now creates its subdirectories 0700 (see
    # `core/fileperms.py` — they were inheriting `0777 & ~umask` under any root
    # Laurelin did not create), and this test is about the import not touching
    # the mode, whatever it is.
    after = dst_ws.ontology_dir.stat().st_mode & 0o777
    assert after == before
    assert after & 0o100, "the owner traverse bit is what the attack stripped"


def test_a_member_inside_another_member_is_refused(source, target, tmp_path):
    """One name cannot be both a file and a directory. Measured: an archive
    holding pipelines/z.py and pipelines/z.py/a.py landed the first and then
    raised a bare FileExistsError from mkdir — a 500, mid-write."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    hostile = _repack(archive, tmp_path, extra=[
        ("pipelines/z.py", b"#\n"), ("pipelines/z.py/a.py", b"#\n"),
    ])
    with pytest.raises(ImportRefused, match="both a file and a directory"):
        import_workspace(hostile, dst_ws, dst_store, ImportOptions())


def test_a_format_version_below_one_is_refused(source, target, tmp_path):
    """Only the upper bound was checked, so format_version 0 — and -1 — were
    read as version 1."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    for version in (0, -1):
        doc = json.loads(_member(archive.read_bytes(), MANIFEST_MEMBER))
        doc["format_version"] = version
        forged = _repack(archive, tmp_path, replace={
            MANIFEST_MEMBER: json.dumps(doc).encode(),
        })
        with pytest.raises(ImportRefused, match="no Laurelin has ever written"):
            import_workspace(forged, dst_ws, dst_store, ImportOptions())


@pytest.mark.parametrize(
    ("table", "mutate", "match"),
    [
        ("datasets", lambda r: dict(r, name="../escaped"), "not a name"),
        ("datasets", lambda r: dict(r, kind="totally-made-up"), "does not have a reader"),
        ("markings", lambda r: dict(r, name="z" * 5000), "not a name"),
        ("dataset_versions", lambda r: dict(r, version="9999999"), "not an integer"),
        ("datasets", lambda r: dict(r, description={"nested": "object"}), "scalar"),
    ],
)
def test_a_row_no_other_code_path_could_have_written_is_refused(
    source, target, tmp_path, table, mutate, match
):
    """Import writes through the backend rather than the routes — deliberately,
    so an unresolvable grant is not dropped — which means the authoring rules
    have to be re-applied here or not at all. Measured: a dataset called
    '../escaped' landed and was then permanently un-writable and
    un-compactable, because catalog.write rejects the name it would have to
    use."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    forged = _repack(archive, tmp_path, replace={
        f"tables/{table}.jsonl": _as_jsonl([mutate(r) for r in _rows_of(archive, table)]),
    })
    with pytest.raises(ImportRefused, match=match):
        import_workspace(forged, dst_ws, dst_store, ImportOptions())
    assert dst_store.list_datasets() == []


def test_a_duplicate_row_is_a_refusal_and_not_a_driver_error(source, target, tmp_path):
    """Only ImportRefused becomes a 409; everything else is a bare 500, which
    is the one status code that tells an operator nothing about an archive they
    are trying to diagnose."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    rows = _rows_of(archive, "datasets")
    forged = _repack(archive, tmp_path, replace={
        "tables/datasets.jsonl": _as_jsonl(rows + [rows[0]]),
    })
    with pytest.raises(ImportRefused, match="refused the archive"):
        import_workspace(forged, dst_ws, dst_store, ImportOptions())
    assert dst_store.list_datasets() == []


# --------------------------------------------------------------------------- what an
# --------------------------------------------------------------------------- import
# --------------------------------------------------------------------------- leaves

def test_a_refused_import_leaves_no_pipeline_behind_an_open_gate(
    source, target, tmp_path
):
    """pipelines_acknowledged() returns True when the state file is absent, so
    writing the gate *after* landing the files made a mid-landing failure turn
    the gate off with attacker pipelines already on disk — reachable by any
    viewer-gated GET /transforms."""
    from laurelin.export import reader

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())
    hostile = _repack(archive, tmp_path, extra=[
        ("pipelines/evil.py", b"raise SystemExit('executed')\n"),
    ])

    real = reader._land_files

    def explode(workspace, staging, files, landed):
        real(workspace, staging, files, landed)
        raise RuntimeError("disk full, halfway through")

    reader._land_files = explode
    try:
        with pytest.raises(RuntimeError):
            import_workspace(hostile, dst_ws, dst_store, ImportOptions())
    finally:
        reader._land_files = real

    assert list(dst_ws.pipelines_dir.glob("*.py")) == []
    assert dst_store.list_datasets() == []
    assert not (dst_ws.root / ".laurelin-import.json").exists()


def test_a_committed_version_never_loses_the_parts_it_names(source, target, tmp_path):
    """The failure handler deleted every written part unconditionally, with the
    comment 'the rows that named them rolled back' — true only before the
    commit. Measured, when a failure landed after it: the rows stayed durable
    and their Parquet was deleted, producing exactly the
    registered-but-missing version this module's docstring promises cannot
    happen.

    Driven by making the audit line fail, because that is the only thing left
    after the commit — which is the point.
    """
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "export.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    real = dst_store.log_audit

    def explode(*args, **kwargs):
        if args and args[0] == "workspace_imported":
            raise RuntimeError("the audit sink went away")
        return real(*args, **kwargs)

    dst_store.log_audit = explode
    try:
        with pytest.raises(RuntimeError):
            import_workspace(archive, dst_ws, dst_store, ImportOptions())
    finally:
        dst_store.log_audit = real

    catalog = DatasetCatalog(dst_ws, dst_store)
    versions = dst_store.list_versions("sales")
    assert versions, "the rows committed, so they are the truth now"
    for version in versions:
        for key in version.files:
            assert catalog.storage.size(key) >= 0, "a committed version lost its part"
    assert catalog.read("sales").num_rows == 2


def test_a_managed_dataset_whose_parts_did_not_arrive_lands_needing_credentials(
    source, target, tmp_path
):
    """The manifest declares intent; the archive decides what arrived.
    Measured, when the manifest was trusted: dropping every data/ member left
    data_state 'included' and a bare FileNotFoundError carrying an absolute
    server path on the first read."""
    from laurelin.export import NeedsCredentials

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    parts = [n for n in _names(archive.read_bytes()) if n.startswith("data/")]
    stripped = _repack(archive, tmp_path, drop=set(parts))
    report = import_workspace(stripped, dst_ws, dst_store, ImportOptions())

    assert report.applied
    assert any("did not carry" in w for w in report.warnings)
    with pytest.raises(NeedsCredentials, match="without its data"):
        DatasetCatalog(dst_ws, dst_store).read("sales")


def test_an_imported_source_and_engine_say_they_need_credentials(
    source, target, tmp_path
):
    """A row whose endpoint was withheld is a shape awaiting a credential, not
    a working registration. Measured: an imported source read back as
    {'url': None} with a null status — indistinguishable from a healthy
    connector until the first sync failed with a driver error."""
    from laurelin.core.models import SourceInfo
    from laurelin.export.reader import needs_credentials

    src_ws, src_store = source
    src_store.upsert_source(SourceInfo(
        name="feed", type="http", dataset="sales",
        config={"url": "https://svc:pw@api.corp/v1"}, created_by="andy",
    ))
    src_store.upsert_engine("trino", "flightsql", "grpc+tls://svc:pw@trino:443",
                            {"k": "v"}, "andy")

    _roundtrip(source, target, tmp_path)
    _, dst_store = target
    assert needs_credentials(dst_store.get_source("feed").config)
    assert dst_store.get_source("feed").last_sync_status == "needs_credentials"
    assert needs_credentials(dst_store.get_engine("trino")["options"])


# --------------------------------------------------------------------------- merging

def test_a_merge_refuses_ontology_grants_for_a_type_the_target_owns(
    source, target, tmp_path
):
    """_evaluate ORs over every matching grant, so an added one can only widen
    — and ontology_grants is keyed on object_type, which --rename-prefix does
    not touch. Measured: a *stale* grant for a type the source had since
    renamed out of its YAML merged onto the destination's own 'report', and a
    viewer went from 403 to reading a row out of a dataset the archive never
    contained."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    src_store.set_grants_for_type("report", [
        Grant(subject_kind=SubjectKind.everyone, subject="", can_view=True,
              can_edit=True).model_dump()
    ])
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    dst_store.upsert_dataset("secret_ds", "the target's own")
    dst_store.set_grants_for_type("report", [
        Grant(subject_kind=SubjectKind.role, subject="admin",
              can_view=True).model_dump()
    ])

    with pytest.raises(ImportRefused, match="object_type 'report'"):
        import_workspace(archive, dst_ws, dst_store,
                         ImportOptions(merge=True, dry_run=True))
    after = {g["subject_kind"] for g in dst_store.grants_for_type("report")}
    assert after == {"role"}


def test_a_merge_refuses_rather_than_overwriting_a_workspace_file(
    source, target, tmp_path
):
    """_land_files used shutil.move, which overwrites, and it ran after the
    commit — so the rollback could not undo it. Measured twice: a same-basename
    ontology file was destroyed, and a different-basename one with a colliding
    api_name made every ontology route 400, including for types the archive
    never mentioned."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    dst_store.upsert_dataset("secret_ds", "the target's own")
    own = dst_ws.ontology_dir / "o.yml"
    own.write_text(
        "object_types:\n"
        "  - api_name: ledger\n"
        "    backing_dataset: secret_ds\n"
        "    primary_key: region\n"
    )
    before = own.read_text()

    with pytest.raises(ImportRefused, match="already has ontology/o.yml"):
        import_workspace(archive, dst_ws, dst_store,
                         ImportOptions(merge=True, dry_run=True))
    assert own.read_text() == before


def test_a_merge_refuses_a_duplicate_api_name_rather_than_bricking_the_ontology(
    source, target, tmp_path
):
    """A different basename declaring the same api_name is the worse case: the
    target's file survives, and load_ontology raises for every type in it."""
    from laurelin.ontology import load_ontology

    src_ws, src_store = source
    dst_ws, dst_store = target
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    dst_store.upsert_dataset("secret_ds", "the target's own")
    (dst_ws.ontology_dir / "own.yml").write_text(
        "object_types:\n"
        "  - api_name: sale\n"
        "    backing_dataset: secret_ds\n"
        "    primary_key: region\n"
        "  - api_name: ledger\n"
        "    backing_dataset: secret_ds\n"
        "    primary_key: region\n"
    )

    with pytest.raises(ImportRefused, match="api_name"):
        import_workspace(archive, dst_ws, dst_store,
                         ImportOptions(merge=True, dry_run=True))
    assert {t.api_name for t in load_ontology(dst_ws.ontology_dir).object_types} == {
        "sale", "ledger"
    }


@pytest.mark.parametrize("kind", ["dashboards", "object_apps", "schedules",
                                  "sources", "engines"])
def test_a_merge_names_the_collision_that_used_to_abort_it_with_a_driver_error(
    source, target, tmp_path, kind
):
    """Measured: a destination sharing one name in any of seven tables aborted
    the apply with a raw IntegrityError — HTTP 500 — and the collision report
    had not mentioned it. That made --merge unusable on any real destination,
    including via the two resolutions the report itself printed."""
    from laurelin.core.models import (
        DashboardInfo,
        DashboardPanel,
        ObjectAppInfo,
        SourceInfo,
    )

    def seed(store, title):
        if kind == "dashboards":
            store.upsert_dashboard(DashboardInfo(
                name="ops", title=title,
                panels=[DashboardPanel(id="p", sql="SELECT 1")], created_by="a"))
        elif kind == "object_apps":
            store.upsert_object_app(ObjectAppInfo(
                name="ops", title=title, object_type="sale", created_by="a"))
        elif kind == "schedules":
            store.upsert_schedule(ScheduleInfo(
                name="ops", trigger="cron", cron="0 0 * * *", action="build",
                created_by="a"))
        elif kind == "sources":
            store.upsert_source(SourceInfo(
                name="ops", type="http", dataset="sales",
                config={"format": title}, created_by="a"))
        else:
            store.upsert_engine("ops", "flightsql", "grpc+tls://h:443", {}, "a")

    src_ws, src_store = source
    dst_ws, dst_store = target
    seed(src_store, "source-side")
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())
    dst_store.upsert_dataset("sales", "the target's own")
    seed(dst_store, "target-side")

    # --rename-prefix resolves the dataset collision the seeding needs, so the
    # only refusal left is the one this test is about.
    with pytest.raises(ImportRefused, match=kind):
        import_workspace(archive, dst_ws, dst_store,
                         ImportOptions(merge=True, dry_run=True,
                                       rename_prefix="copy_"))


def test_a_namespaced_marking_is_renamed_in_the_clearance_checklist_too(
    source, target, tmp_path
):
    """The rebind checklist is what the operator works from, so it has to name
    the marking as it exists *here*. Measured: after a namespaced marking,
    granting exactly what clearances.jsonl said left the principal denied, and
    the rename lived only in a field the checklist does not mention."""
    src_ws, src_store = source
    dst_ws, dst_store = target
    src_store.delete_marking("pii")
    src_store.create_marking("pii", "source meaning")
    src_store.set_explicit_markings("sales", ["pii"])
    src_store.recompute_all_markings()
    src_store.set_clearances("vic", ["pii"])
    archive = tmp_path / "good.tar"
    export_workspace(src_ws, src_store, archive, ExportOptions())

    dst_store.create_marking("pii", "DESTINATION meaning")
    planned = import_workspace(archive, dst_ws, dst_store,
                               ImportOptions(merge=True, dry_run=True))
    report = import_workspace(
        archive, dst_ws, dst_store,
        ImportOptions(merge=True, confirm=planned.report_sha256),
    )

    renamed = report.marking_renames["pii"]
    assert renamed != "pii"
    assert dst_store.get_effective_markings("sales") == [renamed]
    assert report.quarantined_clearances == [
        {"username": "vic", "marking_at_source": "pii", "marking": renamed}
    ]


def test_an_import_never_writes_over_a_part_the_destination_already_has(
    tmp_path, make_store
):
    """**The destination's live governed data, silently replaced.**

    ``_write_part`` calls ``storage.open_output_stream``, which truncates —
    there is no ``O_EXCL`` on that path — and the part-write loop used the
    archive member name verbatim as the destination storage key.
    ``--rename-prefix`` renames only the metadata; it never touched
    ``files_json`` or the member keys. So on the documented *safe* resolution
    for a name collision — a ``note`` reading "imported as 'copy_salaries'",
    not a refusal — the archive's ``data/salaries/parts/<uuid>.parquet`` landed
    on top of the destination's live part of that exact key, which the
    destination's own ``salaries`` still references. Measured end to end
    through ``GET /api/v1/workspace/export`` and
    ``POST /api/v1/workspace/import``: after a repack of one member, the
    original dataset returned the attacker's rows.

    Every archive exported from a workspace keeps that workspace's part keys,
    so a round trip collides on every part by construction, and the archive is
    unsigned (``docs/PORTABILITY.md`` says so) — its Parquet is whatever the
    person holding the tar wanted.

    The sibling this also closes: the pre-commit rollback deletes
    ``written_parts``, and when those keys were the destination's own, a merge
    that failed after the part write deleted the destination's live data.
    """
    ws = Workspace.init(tmp_path / "self", name="self")
    store = make_store(ws)
    catalog = DatasetCatalog(ws, store)
    catalog.write("salaries", pa.table({"who": ["alice", "bob"],
                                        "amount": pa.array([100, 200], pa.int64())}))
    before = catalog.read("salaries").to_pylist()

    archive = tmp_path / "self.tar"
    export_workspace(ws, store, archive, ExportOptions())
    # The archive is unsigned, so its Parquet is whatever the holder wants.
    # Repacking one member with a regenerated (honest) trailer is what makes
    # an overwrite *visible*: without it the clobber writes identical bytes
    # over identical bytes and no assertion about rows could see it.
    tampered = pa.table({"who": ["attacker"], "amount": pa.array([999999], pa.int64())})
    sink = pa.BufferOutputStream()
    pq.write_table(tampered, sink)
    _swap_member(archive, "data/salaries/parts/", sink.getvalue().to_pybytes())

    planned = import_workspace(
        archive, ws, store,
        ImportOptions(merge=True, dry_run=True, rename_prefix="copy_"),
    )
    assert planned.dataset_renames == {"salaries": "copy_salaries"}
    report = import_workspace(
        archive, ws, store,
        ImportOptions(merge=True, rename_prefix="copy_",
                      confirm=planned.report_sha256),
    )
    assert report.applied

    # The destination's own dataset reads exactly what it read before.
    assert DatasetCatalog(ws, store).read("salaries").to_pylist() == before
    # The relocation is reported rather than silent.
    assert any("already uses" in w for w in report.warnings), report.warnings
    # And the imported copy points at the parts that were actually written, so
    # the relocation did not trade a clobber for a dangling reference: it reads
    # the archive's (tampered) rows, under its own name, where it belongs.
    assert DatasetCatalog(ws, store).read("copy_salaries").to_pylist() == [
        {"who": "attacker", "amount": 999999}
    ]
    # Structurally: the two datasets share no storage key at all.
    src_keys = set(store.get_version("salaries", None).files)
    copy_keys = set(store.get_version("copy_salaries", None).files)
    assert src_keys and copy_keys and src_keys.isdisjoint(copy_keys)


def _swap_member(archive, member_prefix: str, replacement: bytes) -> None:
    """Rewrite the first member under `member_prefix`, regenerating TRAILER.json.

    ``_verify_trailer`` hashes every arriving member against the trailer, so a
    partial tamper is already refused; a full repack is the unsigned-archive
    limitation ``docs/PORTABILITY.md`` discloses, and it is the shape that
    turns "an import of lies" into "the destination's data replaced".
    """
    import hashlib

    members = []
    with tarfile.open(archive) as tar:
        for info in tar.getmembers():
            data = tar.extractfile(info).read() if info.isreg() else b""
            members.append((info.name, data))
    swapped = False
    out = []
    for name, data in members:
        if name == "TRAILER.json":
            continue
        if not swapped and name.startswith(member_prefix):
            data, swapped = replacement, True
        out.append((name, data))
    assert swapped, f"no member under {member_prefix!r}"
    digests, total = {}, 0
    with tarfile.open(archive, "w", format=tarfile.PAX_FORMAT) as tar:
        for name, data in out:
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.type = len(data), 0o600, tarfile.REGTYPE
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            tar.addfile(info, io.BytesIO(data))
            digests[name] = {"sha256": hashlib.sha256(data).hexdigest(),
                             "bytes": len(data)}
            total += len(data)
        trailer = json.dumps({"members": digests, "member_count": len(digests),
                              "total_bytes": total}, indent=2).encode() + b"\n"
        info = tarfile.TarInfo("TRAILER.json")
        info.size, info.mode, info.type = len(trailer), 0o600, tarfile.REGTYPE
        info.uid = info.gid = 0
        info.uname = info.gname = ""
        tar.addfile(info, io.BytesIO(trailer))
